# The URL the site will be built for
base_url = "https://v3lmx.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "papermod"

taxonomies = [
    { name = "tags", feed = true }
]

author = "v3lmx"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
custom_css = []

[extra.papermod]
title = "v3lmx"
default_theme = "auto"
theme = "dark"
language_direction = "auto"
keywords = ["v3lmx"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
edit_post_url = "https://github.com/v3lmx/blog"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    # { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/about/", title = "About" },
    { url = "$BASE_URL/tags/", title = "Tags" },
    { url = "https://getzola.org/", title = "Zola", is_external = true }
]

home_title = "v3lmx"
home_content = "Software engineer, Rust enthusiast"
social_icons = [
    { url = "https://github.com/v3lmx", title = "GitHub", icon = "github" },
]
